services:
  ray_server_train:
    build: .                        # Build from the Dockerfile in the same folder
    container_name: train_server
    shm_size: "2gb"
    environment:
    - RAY_memory_usage_threshold=0.95
    - RAY_memory_monitor_refresh_ms=0
    ports:
      - "8000:8000"
    mem_limit: 4g  